### PR TITLE
Make pyssht an installable package

### PR DESCRIPTION
**Pull request by EiffL**
In its present form, pyssht is not a proper python package. I have modified the setup.py and moved the source files to an isolated pyssht directory so that it can now be installed easily with the following command:
```
python setup.py install --user
```
It shouldn't change the previous behavior, you can still compile the files with `python setup.py build_ext --inplace` command.

### CODE REVIEW

**Comment by EiffL** [comment]
Hi @jasonmcewen what do you think of this PR ? If you like it and also approve https://github.com/astro-informatics/massmappy/pull/1 people can install massmappy in one command

**Comment by jasonmcewen** [comment]
@EiffL The public version of ssht was not updated with our recent local updates.  I've just pushed an update to the public version now.  This seems to have caused a merge conflict with pyssht.pyx.  Could you take a look at the conflicts when you get a chance?  When they're resolved we can merge the PR.

**Comment by EiffL** [comment]
Awesome, thanks @jasonmcewen . I'll update my fork with your updates

**Comment by mdavezac** [comment]
Thanks, @EiffL. We've actually gone one further now. `pyssht` is now on [pypi](https://pypi.org/project/pyssht/), which means it can be installed with `pip install pyssht`.

We've decided to go fully open-source very soon, so we will be archiving the astro-informatics/ssht and making the currently private repo public under the name... /astro-informatics/ssht. As a result you may find your fork no longer leads here. Thanks again.

**Pull request closed without merging**
